
maps:
  - apt
    - libproj-dev
    - libgeos-dev
  - pip install folium
  - pip install fileupload
  - conda
    - channels
      - conda-forge
    - dependencies
      - python
      - matplotlib
      - basemap

astro-stuff:
  - conda install -c astropy/label/openastronomy pyephem

presentation:
  - pip:
    - jupyter_contrib_nbextensions
    - RISE
    - jupyter-wysiwyg
    - jupyter nbextension install [--user] --py fileupload
    - jupyter nbextension enable [--user] --py fileupload

