channels:
  - conda-forge
dependencies:
  - appmode
  - numpy
  - ipywidgets
  - pandas
  - scikit-learn
  - scipy
  - seaborn 
  - opencv
  - nbextension
  
  - pip:
    - jupyter_contrib_nbextensions
    - RISE
    - jupyter-wysiwyg
  

