channels:
  - conda-forge
dependencies:
  - appmode
  - numpy
  - ipywidgets
  - pandas
  - scikit-learn
  - scipy
  - seaborn 
pip:
  - pip install fileupload
  - jupyter nbextension install [--user] --py fileupload
  - jupyter nbextension enable [--user] --py fileupload
    

